{% set name = "conda-forge-ci-setup" %}
{% set version = "3.0.12" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  path: .

build:
  number: 0
  script:
    - cp {{ os.environ["FEEDSTOCK_ROOT"] }}/LICENSE.txt ${RECIPE_DIR}/LICENSE.txt            # [linux]
    - cp ${RECIPE_DIR}/../LICENSE.txt ${RECIPE_DIR}/LICENSE.txt                              # [osx]
    - COPY "%RECIPE_DIR%\\..\\LICENSE.txt" "%RECIPE_DIR%\\LICENSE.txt"                       # [win]
    - if not exist "%LIBRARY_BIN%" mkdir "%LIBRARY_BIN%"                                                                 # [win]
    - mkdir -p "${PREFIX}/bin"                                                                                           # [unix]
    - COPY "%RECIPE_DIR%\\run_conda_forge_build_setup_win.bat" "%SCRIPTS%\\run_conda_forge_build_setup.bat"              # [win]
    - cp "${RECIPE_DIR}/run_conda_forge_build_setup_osx" "${PREFIX}/bin/run_conda_forge_build_setup"                     # [osx]
    - cp "${RECIPE_DIR}/run_conda_forge_build_setup_linux" "${PREFIX}/bin/run_conda_forge_build_setup"                   # [linux]
    - cd "%RECIPE_DIR%"   # [win]
    - cd "${RECIPE_DIR}"  # [unix]
    - "{{ PYTHON }} -m pip install . --no-deps --ignore-installed --no-cache-dir -vvv"
    - echo "${RECIPE_DIR}"
  entry_points:
    - ff_ci_pr_build = conda_forge_ci_setup.ff_ci_pr_build:main
    - upload_or_check_non_existence = conda_forge_ci_setup.upload_or_check_non_existence:main
    - setup_conda_rc = conda_forge_ci_setup.build_utils:setup_conda_rc
    - upload_package = conda_forge_ci_setup.build_utils:upload_package
    - mangle_compiler = conda_forge_ci_setup.build_utils:mangle_compiler
    - make_build_number = conda_forge_ci_setup.build_utils:make_build_number
    - mangle_homebrew = conda_forge_ci_setup.mangle_homebrew:main
    - validate_recipe_outputs = conda_forge_ci_setup.feedstock_outputs:main
  skip: True  # [py2k]

requirements:
  host:
    - python
    - pip
  run:
    - python
    - conda >=4.3
    - conda-env
    - click
    - jinja2
    - anaconda-client
    - conda-build 3.*
    - vs2008_express_vc_python_patch  # [win]
    - shyaml  # [osx]
    - jq      # [osx]
    - requests
    - ruamel_yaml
    - pip
    - pyyaml
    - m2-git  # [win]
    - git     # [unix]

test:
  # ensure that all variants of cuda_compiler_version are tested
  requires:                                    # [linux and cuda_compiler_version not in (undefined, "None")]
    - cudatoolkit {{ cuda_compiler_version }}  # [linux and cuda_compiler_version not in (undefined, "None")]
  commands:
    - if not exist "%PREFIX%\\Scripts\\run_conda_forge_build_setup.bat" exit 1    # [win]
    - test -f "${PREFIX}/bin/run_conda_forge_build_setup"                         # [unix]
    - ff_ci_pr_build --help
    - upload_or_check_non_existence --help
    - setup_conda_rc --help
    - upload_package --help
    - make_build_number --help
    - mangle_homebrew --help
    - validate_recipe_outputs --help


about:
  home: https://github.com/conda-forge/conda-forge-build-setup-feedstock
  summary: A package installed by conda-forge each time a build is run on CI. This package has side-effects to your conda config.
  license: BSD-3-Clause
  license_file: LICENSE.txt

extra:
  recipe-maintainers:
    - conda-forge/core
