{% set name = "conda-forge-ci-setup" %}
{% set version = "2.0.5" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

build:
  number: 0
  script:
    - if not exist "%LIBRARY_BIN%" mkdir "%LIBRARY_BIN%"                                                                 # [win]
    - mkdir -p "${PREFIX}/bin"                                                                                           # [unix]
    - COPY "%RECIPE_DIR%\\run_conda_forge_build_setup_win.bat" "%SCRIPTS%\\run_conda_forge_build_setup.bat"              # [win]
    - cp "${RECIPE_DIR}/run_conda_forge_build_setup_osx" "${PREFIX}/bin/run_conda_forge_build_setup"                     # [osx]
    - cp "${RECIPE_DIR}/run_conda_forge_build_setup_linux" "${PREFIX}/bin/run_conda_forge_build_setup"                   # [linux]
    - cd "%RECIPE_DIR%"   # [win]
    - cd "${RECIPE_DIR}"  # [unix]
    - "{{ PYTHON }} -m pip install . --no-deps --ignore-installed --no-cache-dir -vvv"
    - echo "${RECIPE_DIR}"
  entry_points:
    - ff_ci_pr_build = conda_forge_ci_setup.ff_ci_pr_build:main
    - upload_or_check_non_existence = conda_forge_ci_setup.upload_or_check_non_existence:main
    - setup_conda_rc = conda_forge_ci_setup.build_utils:setup_conda_rc
    - upload_package = conda_forge_ci_setup.build_utils:upload_package
    - mangle_compiler = conda_forge_ci_setup.build_utils:mangle_compiler
    - make_build_number = conda_forge_ci_setup.build_utils:make_build_number
  skip: True  # [py2k]

requirements:
  host:
    - python
    - pip
  run:
    - python
    - conda >=4.3
    - conda-env
    - click
    - jinja2
    - anaconda-client
    - conda-build 3.*
    - vs2008_express_vc_python_patch  # [win]

test:
  commands:
    - if not exist "%PREFIX%\\Scripts\\run_conda_forge_build_setup.bat" exit 1    # [win]
    - test -f "${PREFIX}/bin/run_conda_forge_build_setup"                         # [unix]
    - ff_ci_pr_build --help
    - upload_or_check_non_existence --help
    - setup_conda_rc --help
    - upload_package --help
    - make_build_number --help


about:
  home: https://github.com/conda-forge/conda-forge-build-setup-feedstock
  summary: A package installed by conda-forge each time a build is run on CI. This package has side-effects to your conda config.
  license: BSD 3-clause

extra:
  recipe-maintainers:
    - isuruf
    - jakirkham
    - jjhelmus
    - msarahan
    - mwcraig
    - ocefpaf
    - patricksnape
    - pelson
    - scopatz
    - mariusvniekerk
    - CJ-Wright
