travis:
  secure:
    BINSTAR_TOKEN: DGja/KGwhOuJJ6xPVm3ap7XUpcY/oloT1ekj1GgQeLLmmh8Veto/SyscM0rJZC+GuqQkufQvpa1RzbcSc11vUNybqumBXlXx8FbYl83iv0N1ihApX86lZsIU2llnwkTqKGx5ga0cdut0SN7VQwm/19CABWu6Rcs+wOVDCfjDOk88QjcuEaApu6YON2hoSoqEL7A+SOgR360Cm8iwpAtv0LtuPxLahDKUr+CIngpR9QLyNHRlHjevhOoEQlqAkDRdf00QsW/E8hNUildfP9YPab0VrBFDdMvPiIeCAi4V3FtxcMZD/Zv7cBhSGD4vMyIKHAny9oPkSy3oqFA8oJhGdcEjYuyqCS9E9xKq6dWh/v1kL3/hPtilVIfhfwX+kQS1ndghrjRvEWesbycNtc5l5KpN9QjSyTbnNhyObEmYHn6x1vPnEhm1uRBekl84nOwu0x6dkPtjQiO420dYQri2U/FRpkNfvYKhwCyUSyJhLvfttBQuWhO9pPus8Sxkz19l37EqPe8rJvkXaKk6RjxjqTmn140hDHwEL7h7GxuVxVZDqve1ibFP3jJO5wVrQ7oHWaw9JTs+PR8yZhvmjrNbVLueAqbC3I1Mz7DcghtDn+1jqD/+7T1+K1v5t3KMn/zvaw++gEd+vyMSEtZIU8dqlelnACZ9eGvkppeHih+eUvw=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
compiler_stack: comp7
max_py_ver: '37'
max_r_ver: '35'
provider:
  linux_aarch64: native
  linux_ppc64le: azure
  win: azure
  osx: circle
  linux: travis
